services:
    app:
        build: .
        container_name: qiskit_job_manager
        command: python -c "from qiskit_job_manager_server import run_server; run_server()"
        ports:
          - 8000:8000

    web:
        build: nginx
        container_name: nginx
        ports:
          - 80:80
          - 443:443
        depends_on:
          - app